### ISSUE TITLE
Implement Gcode "?"

### ISSUE THREAD

**Issue by mboremski** [matthewwachter/py-mirobot#2]
Could you implement a function to read back the actual position pls?

**Comment by matthewwachter** [comment]
Added that in the form of get_status(callback=None)

and you callback might be something like recv_status(status) where status is a dictionary of the information. I used a bit of regex to parse the message coming back but it's a bit dirty. If anyone feels like cleaning that up let me know :)

**Comment by mboremski** [comment]
An issue-reference in your commit would have been nice.. ;-)

Thank you for your really fast reply.
will give that a try later.

**Comment by mboremski** [comment]
found a typo in Line 151
`self._send_msg` should be `self.send_msg`
